ports:
  - port: 9001
    onOpen: open-preview
  - port: 9002
    onOpen: open-browser
  - port: 9005-9010
    onOpen: ignore
tasks:
  - command: python3 -m http.server 9001
    name: Open 9001 in Preview
  - command: python3 -m http.server 9002
    name: Open 9002 in Browser
  - command: python3 -m http.server 9003
    name: SHOW notification for 9003
  - command: python3 -m http.server 9005
    name: NO notification for 9005
