
ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: >
    python3 -m pip install -r requirements.txt &&
    python3 manage.py migrate
  command: >
    echo "from locallibrary.settings import *" > locallibrary/local_settings.py &&
    echo "ALLOWED_HOSTS = ['*']" >> locallibrary/local_settings.py &&
    export DJANGO_SETTINGS_MODULE=locallibrary.local_settings &&
    python3 manage.py runserver 0.0.0.0:8080
github:
    prebuilds:
        pullRequestsFromForks: true

vscode:
  extensions:
    - test.on-debug-adapter-protocol-tracker@0.0.1-8e3a6de7abff27e829c34602633017867ce64c6eab094a2c57b55075c211d9f4